# This code is in the public domain; it can be used
# for any purpose with absolutely no restrictions

import urllib2
import csv
import datetime
from datetime import datetime

TURBINE_CSV = "http://susdash-pilot.cwru.edu/amcharts/data_files/veale_wind.csv"

def retrieve_all_rows():
    """Returns a list of tuples of the form:

       (datetime, production, consumption)

       where datetime is a datetime.datetime object representing the row
       collection time, production is an int holding the number of kilowatts
       generated by the turbine at that point in time, and consumption is also
       an int holding the number of kilowatts consumed by Veale Center"""

    now = datetime.now()
    results = []

    req = urllib2.urlopen(TURBINE_CSV)
    
    # csv.reader only requires an object that returns a string when next()
    # is called on it, which urllib2.urlopen() conveniently returns!
    csvReader = csv.reader(req)
    for row in csvReader:
        time_raw = row[0]
        consumption = int(row[1])
        production = int(row[2])
        
        time_parsed = datetime.strptime(time_raw, '%I:%M %p')
        final = datetime(now.year, now.month, now.day, time_parsed.hour, time_parsed.minute)
        
        results.append((final, production, consumption))
    return results
        
